spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0
linux-do:
  oauth2:
    client:
      registration:
        client-id: sxBugtXPNGrrKshlKeY8YELJWLiRZuUv
        client-secret: H20CcxJWEX9FYikaSIzNpWTuzqXudZql
        redirect-uri:  https://local.3www.me/oauth2/callback
        authorization-grant-type: authorization_code
        scope: read,write
      provider:
        authorization-uri: https://connect.linux.do/oauth2/authorize
        token-uri: https://connect.linux.do/oauth2/token
        user-info-uri: https://connect.linux.do/api/user
        user-name-attribute: id